name: Feature testing

on:
  push:
    branches:
      - add-feature

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ vars.AWS_REGION  }}
        run: |
          echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
          echo ${{ vars.AWS_REGION  }} | sed 's/./& /g'

# jobs:
#   # Install dependencies
#   call-install-workflow:
#     uses: ./.github/workflows/install-deps.yml

#   # Job to deploy the API
#   call-deploy-api-workflow:
#     uses: ./.github/workflows/deploy-feature.yml
#     needs: call-install-workflow
#     secrets:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       DB_URL: ${{ secrets.DB_URL }}
#       DB_URL_NON_POOLING: ${{ secrets.DB_URL_NON_POOLING }}
#       GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
#       GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
